# Config file for automatic testing at travis-ci.com
language: python

python:
  - '3.7'
  - '3.6'

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements.txt

# cache installation
cache:
  - pip

# Command to run tests, e.g. python setup.py test
script:
  - python -m unittest tests.test_script
